### ISSUE TITLE
New release points to commit not part of the master branch

### ISSUE THREAD

**Issue by kevinvanrijn** [Kikobeats/top-user-agents#19]
The tag https://github.com/Kikobeats/top-user-agents/releases/tag/v1.0.51 points to commit ~~4bb7ddb6a36dc16a3289c5c4238e546417e57942~~ which isn't part of the master branch. It should've been pointed at c895dcbea2836901b6fb9c648017ce9cf9c064e9 instead.

GitHub also echoes this:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

The cause seems to be an earlier Actions run which created the tag:

https://github.com/Kikobeats/top-user-agents/actions/runs/4102378754/jobs/7075264231#step:6:102

Consider force pushing the tag with something like:

```
git reset c895dcbea2836901b6fb9c648017ce9cf9c064e9
git tag -f v1.0.51
git push -f origin refs/tags/v1.0.51:refs/tags/v1.0.51
```

**Comment by Kikobeats** [comment]
thanks for this. It looks like GitHub Actions is messing up.

I forced to point the right commit:

```
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:Kikobeats/top-user-agents.git
 + ab3b689...c895dcb v1.0.51 -> v1.0.51 (forced update)
```

🙂
