### ISSUE TITLE
Update to got@~12.5.3 ?

### ISSUE THREAD

**Issue by karlhorky** [Kikobeats/top-user-agents#20]
Hi @Kikobeats! 👋 Hope you are well.

Since `got@~11.8.6` depends on `cacheable-request@^7.0.2` and [`GHSA-8x6c-cv3v-vp6g`](https://github.com/advisories/GHSA-8x6c-cv3v-vp6g) outlines a vulnerability in `cacheable-request` versions before `10.2.7`, maybe it would be a good time to upgrade to `got@^12.5.3` or `got@~12.5.3` - what do you think?

According to [the `12.0.0` release notes](https://github.com/sindresorhus/got/releases/tag/v12.0.0), the main breaking changes seem to be:

- [`got` is now pure ESM](https://github.com/sindresorhus/got/releases/tag/v12.0.0#:~:text=This%20package%20is%20now%20pure%20ESM)
- [Node.js version support changed to >= v14](https://github.com/sindresorhus/got/releases/tag/v12.0.0#:~:text=Required%20Node.js%20%3E%3D14)
- [improved option normalization](https://github.com/sindresorhus/got/releases/tag/v12.0.0#:~:text=Improved%20option%20normalization)

**Comment by Kikobeats** [comment]
Eventually yes, but first ESM ecosystem should stable.

In any case, library is essentially a JSON, I think update here got isn't too relevant.

**Comment by karlhorky** [comment]
> first ESM ecosystem should stable

Ok, when will the ESM ecosystem be stable in your opinion? When Node.js v14 security support ends at end of April 2023?

**Comment by Kikobeats** [comment]
It's going to be a slow transition – there are part of Internet that will never be ESM.

More or less ⅓ of my dependencies are ESM right now

**Comment by karlhorky** [comment]
Oh, I didn't mean to ask when the other parts of the ecosystem are switching to ESM, I'm aware of the slow pace + compatibility problems, I file a lot of bugs / PRs to help fix this.

What I meant to ask is; what is your opinion on when `top-user-agents` or any of your other packages can transition to `got@>=15.0.0`? (since I interpreted that you meant that there is some prerequisite timeline of "stability" in the ecosystem).

The reason I ask is because I think lots of packages and authors think it's stable already now, and Node.js v14 going EOL will further make this more stable.

**Comment by Kikobeats** [comment]
Latest version is using got@12; can you verify at your end?
