### ISSUE TITLE
new source?

### ISSUE THREAD

**Issue by fenopa** [Kikobeats/top-user-agents#28]
your source appears to be dead now.

**Comment by Kikobeats** [comment]
oh thanks for notifying - Fortunately, I have a backup of users agents, but yea, I have to figure oute a new source.

**Comment by fenopa** [comment]
> suggestions?

no idea, I was using your list. I looked for a new regularly updated source as well but couldn't find anything.

**Comment by Kikobeats** [comment]
@fenopa I'm creating my own suggestion – it will be shipped soon!
