### ISSUE TITLE
Source of user agents

### ISSUE THREAD

**Issue by CyberMew** [Kikobeats/top-user-agents#4]
Just checking, may I know how do you find/know what are the recent top 50 agents?

**Comment by CyberMew** [comment]
My bad, just saw the link, it is based on the traffic on their site. Have you checked out whatismybrowser user agent before? I think they always have an updated list as well, and is also configurable.

**Comment by Kikobeats** [comment]
can you provide the link you suggested as a source of truth?

**Comment by CyberMew** [comment]
This was the one I was referring to https://developers.whatismybrowser.com/api/docs/v2/sample-code/database-search
